"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { videoEmbedUrl } from "@/lib/video-utils";
type Video = { id: string; url: string; produtoId: string; nome: string; codigo: string; imagem: string | null; preco: number };
export default function ReelsClient({ videos, catalogo = "varejo" }: { videos: Video[]; catalogo?: string }) {
  const refs = useRef<Record<string, HTMLElement | null>>({}); const [ativo, setAtivo] = useState("");
  useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(e => { if (e.isIntersecting) setAtivo((e.target as HTMLElement).dataset.id ?? ""); }), { threshold: 0.7 }); Object.values(refs.current).forEach(el => el && observer.observe(el)); return () => observer.disconnect(); }, [videos.length]);
  if (!videos.length) return <main className="min-h-screen bg-black text-white flex items-center justify-center p-6 text-center"><div><h1 className="text-xl font-semibold">Ainda não há vídeos neste catálogo</h1><p className="mt-2 text-sm text-white/70">Cadastre vídeos ativos nos produtos para eles aparecerem aqui.</p></div></main>;
  return <main className="h-screen overflow-y-auto snap-y snap-mandatory bg-black">{videos.map(v => { const produtoUrl = `/${catalogo}/produto/${v.produtoId}`; const shareText = encodeURIComponent(`Olá, tenho interesse no produto ${v.nome} (${v.codigo}). ${produtoUrl}`); return <section key={v.id} data-id={v.id} ref={el => { refs.current[v.id] = el; }} className="h-screen snap-start relative flex items-center justify-center"><iframe src={ativo === v.id ? `${videoEmbedUrl(v.url)}${videoEmbedUrl(v.url).includes("?") ? "&" : "?"}autoplay=1&muted=1` : undefined} loading="lazy" title={v.nome} className="h-full w-full max-w-md" allow="autoplay; fullscreen; picture-in-picture" allowFullScreen /> <div className="absolute bottom-8 left-5 right-5 max-w-md text-white drop-shadow-lg"><Link href={produtoUrl}><p className="font-semibold">{v.nome}</p><p className="text-sm opacity-80">{v.codigo} · R$ {v.preco.toFixed(2).replace(".", ",")}</p></Link><div className="mt-3 flex gap-2"><Link href={produtoUrl} className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-black">Ver produto e adicionar</Link><a href={`https://wa.me/?text=${shareText}`} target="_blank" rel="noreferrer" className="rounded-lg bg-green-600 px-4 py-2 text-sm font-semibold text-white">WhatsApp</a></div></div></section>; })}</main>;
}
