"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Grade = { id: string; nome: string; tipo: string; itens: { id: string; valor: string }[] };
export default function ParametrosPage() {
  const [grades, setGrades] = useState<Grade[]>([]); const [nome, setNome] = useState(""); const [tipo, setTipo] = useState("LETRA"); const [itens, setItens] = useState(""); const [erro, setErro] = useState("");
  async function carregar() { const r = await fetch("/api/grades"); const d = await r.json(); if (r.ok) setGrades(d); }
  useEffect(() => { carregar(); }, []);
  async function criar() { setErro(""); const r = await fetch("/api/grades", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ nome, tipo, itens: itens.split(",").map(v => v.trim()).filter(Boolean) }) }); const d = await r.json(); if (!r.ok) setErro(d.erro ?? "Não foi possível criar a grade."); else { setNome(""); setItens(""); carregar(); } }
  return <div className="max-w-4xl space-y-6"><div><h1 className="text-2xl font-bold">Parâmetros</h1><p className="text-sm text-gray-500 mt-1">Cadastros usados ocasionalmente no sistema.</p></div><div className="grid md:grid-cols-2 gap-4"><Link href="/categorias" className="bg-white border rounded-xl p-5 hover:border-black"><b>Categorias e subcategorias</b><p className="text-sm text-gray-500 mt-1">Organize os grupos de produtos.</p></Link><Link href="/estoque/movimentacoes" className="bg-white border rounded-xl p-5 hover:border-black"><b>Logs de estoque</b><p className="text-sm text-gray-500 mt-1">Histórico de movimentações e ajustes.</p></Link></div><section className="bg-white border rounded-xl p-5 space-y-4"><h2 className="font-semibold">Grades de tamanho</h2>{erro && <p className="text-sm text-red-600">{erro}</p>}<div className="grid md:grid-cols-4 gap-2"><input className="border rounded-lg px-3 py-2 text-sm" placeholder="Nome (ex.: P ao GG)" value={nome} onChange={e => setNome(e.target.value)} /><select className="border rounded-lg px-3 py-2 text-sm" value={tipo} onChange={e => setTipo(e.target.value)}><option value="LETRA">Letras</option><option value="NUMERO">Números</option></select><input className="border rounded-lg px-3 py-2 text-sm md:col-span-1" placeholder="Itens: P, M, G, GG" value={itens} onChange={e => setItens(e.target.value)} /><button onClick={criar} className="bg-black text-white rounded-lg px-3 py-2 text-sm">Cadastrar grade</button></div><div className="divide-y">{grades.map(g => <div key={g.id} className="py-3 flex justify-between text-sm"><span>{g.nome}</span><span className="text-gray-500">{g.itens.map(i => i.valor).join(" · ")}</span></div>)}</div></section></div>;
}
