"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Grade={id:string;nome:string;tipo:string;ativo:boolean;itens:{valor:string}[]}; type Cor={id:string;nome:string;hexCor:string|null;ativo:boolean};
export default function ParametrosPage(){
 const [grades,setGrades]=useState<Grade[]>([]),[cores,setCores]=useState<Cor[]>([]),[nome,setNome]=useState(""),[tipo,setTipo]=useState("LETRA"),[itens,setItens]=useState(""),[novaCor,setNovaCor]=useState(""),[hexCor,setHexCor]=useState("#000000"),[erro,setErro]=useState("");
 async function carregar(){const [g,c]=await Promise.all([fetch("/api/grades?admin=1"),fetch("/api/cores?admin=1")]);const gd=await g.json(),cd=await c.json();if(g.ok)setGrades(gd);if(c.ok)setCores(cd)} useEffect(()=>{carregar().catch(()=>setErro("Não foi possível carregar os parâmetros."))},[]);
 async function acao(url:string,method:string,body:any){const r=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)setErro((await r.json()).erro??"Operação não realizada.");else{setErro("");carregar()}}
 const editar=(x:any,t:string)=>{const v=window.prompt("Novo nome",x.nome);if(v?.trim()&&v.trim()!==x.nome)acao(t,"PATCH",{id:x.id,nome:v.trim(),hexCor:x.hexCor,ativo:x.ativo})};
 return <div className="max-w-5xl space-y-6"><div><h1 className="text-2xl font-bold">Parâmetros</h1><p className="text-sm text-gray-500 mt-1">Cadastros usados ocasionalmente no sistema.</p></div><div className="grid md:grid-cols-2 gap-4"><Link href="/categorias" className="bg-white border rounded-xl p-5"><b>Categorias e subcategorias</b><p className="text-sm text-gray-500 mt-1">Organize os grupos de produtos.</p></Link><Link href="/estoque/movimentacoes" className="bg-white border rounded-xl p-5"><b>Logs de estoque</b><p className="text-sm text-gray-500 mt-1">Histórico de movimentações.</p></Link></div>{erro&&<p className="text-sm text-red-600 bg-red-50 p-3 rounded-lg">{erro}</p>}
 <section className="bg-white border rounded-xl p-5 space-y-4"><h2 className="font-semibold">Cores globais</h2><div className="grid md:grid-cols-[1fr_100px_140px] gap-2"><input className="border rounded-lg px-3 py-2 text-sm" placeholder="Nome da cor" value={novaCor} onChange={e=>setNovaCor(e.target.value)}/><input type="color" className="h-10 w-full border rounded-lg" value={hexCor} onChange={e=>setHexCor(e.target.value)}/><button onClick={()=>acao("/api/cores","POST",{nome:novaCor,hexCor})} className="bg-black text-white rounded-lg px-3 py-2 text-sm">Cadastrar cor</button></div><div className="divide-y">{cores.map(c=><div key={c.id} className="py-3 flex justify-between text-sm"><span className={!c.ativo?"text-gray-400 line-through":""}><i className="inline-block w-4 h-4 rounded-full mr-2 align-middle border" style={{backgroundColor:c.hexCor??"#ddd"}}/>{c.nome} {!c.ativo&&"(inativa)"}</span><span className="flex gap-2"><button onClick={()=>editar(c,"/api/cores")} className="text-blue-600">Alterar</button><button onClick={()=>acao("/api/cores","PATCH",{id:c.id,nome:c.nome,hexCor:c.hexCor,ativo:!c.ativo})} className="text-gray-600">{c.ativo?"Inativar":"Ativar"}</button><button onClick={()=>window.confirm("Excluir esta cor?")&&acao("/api/cores","DELETE",{id:c.id})} className="text-red-600">Excluir</button></span></div>)}</div></section>
 <section className="bg-white border rounded-xl p-5 space-y-4"><h2 className="font-semibold">Grades de tamanho</h2><div className="grid md:grid-cols-4 gap-2"><input className="border rounded-lg px-3 py-2 text-sm" placeholder="Nome (ex.: P ao GG)" value={nome} onChange={e=>setNome(e.target.value)}/><select className="border rounded-lg px-3 py-2 text-sm" value={tipo} onChange={e=>setTipo(e.target.value)}><option value="LETRA">Letras</option><option value="NUMERO">Números</option></select><input className="border rounded-lg px-3 py-2 text-sm" placeholder="Itens: P, M, G, GG" value={itens} onChange={e=>setItens(e.target.value)}/><button onClick={()=>acao("/api/grades","POST",{nome,tipo,itens:itens.split(",").map(v=>v.trim()).filter(Boolean)})} className="bg-black text-white rounded-lg px-3 py-2 text-sm">Cadastrar grade</button></div><div className="divide-y">{grades.map(g=><div key={g.id} className="py-3 flex justify-between text-sm"><span className={!g.ativo?"text-gray-400 line-through":""}><b>{g.nome}</b> · {g.itens.map(i=>i.valor).join(" · ")} {!g.ativo&&"(inativa)"}</span><span className="flex gap-2"><button onClick={()=>editar(g,"/api/grades")} className="text-blue-600">Alterar</button><button onClick={()=>acao("/api/grades","PATCH",{id:g.id,nome:g.nome,ativo:!g.ativo})} className="text-gray-600">{g.ativo?"Inativar":"Ativar"}</button><button onClick={()=>window.confirm("Excluir esta grade?")&&acao("/api/grades","DELETE",{id:g.id})} className="text-red-600">Excluir</button></span></div>)}</div></section></div>;
}
